export const CANONICAL_APPLICATION_STAGES = [
  'awaiting_cv',
  'cv_processing',
  'ready_for_review',
  'shortlisted',
  'interview',
  'hired',
  'rejected',
  'withdrawn',
] as const

export const COMMUNICATION_STATES = ['pending', 'sent', 'failed', 'intentionally_skipped'] as const

export type RecruitingLocale = 'en' | 'ar'
export type CanonicalApplicationStage = (typeof CANONICAL_APPLICATION_STAGES)[number]
export type CommunicationState = (typeof COMMUNICATION_STATES)[number]

const LEGACY_STAGE_MAP: Record<string, CanonicalApplicationStage> = {
  cv_request: 'awaiting_cv',
  cv_upload: 'awaiting_cv',
  cv_received: 'cv_processing',
  screening: 'cv_processing',
  screening_complete: 'ready_for_review',
  review_pending: 'ready_for_review',
  scheduled: 'interview',
  offered: 'shortlisted',
  offer_sent: 'shortlisted',
}

export const STAGE_LABELS: Record<RecruitingLocale, Record<CanonicalApplicationStage, string>> = {
  en: {
    awaiting_cv: 'Waiting for CV',
    cv_processing: 'Processing CV',
    ready_for_review: 'Ready for review',
    shortlisted: 'Shortlisted',
    interview: 'Interview',
    hired: 'Hired',
    rejected: 'Rejected',
    withdrawn: 'Withdrawn',
  },
  ar: {
    awaiting_cv: 'بانتظار السيرة الذاتية',
    cv_processing: 'معالجة السيرة الذاتية',
    ready_for_review: 'جاهز للمراجعة',
    shortlisted: 'في القائمة المختصرة',
    interview: 'المقابلة',
    hired: 'تم التعيين',
    rejected: 'مرفوض',
    withdrawn: 'منسحب',
  },
}

export const COMMUNICATION_LABELS: Record<RecruitingLocale, Record<CommunicationState, string>> = {
  en: {
    pending: 'Pending',
    sent: 'Sent',
    failed: 'Failed',
    intentionally_skipped: 'Intentionally skipped',
  },
  ar: {
    pending: 'قيد الانتظار',
    sent: 'تم الإرسال',
    failed: 'فشل الإرسال',
    intentionally_skipped: 'تم التجاوز عمداً',
  },
}

export const ACTION_LABELS: Record<RecruitingLocale, Record<string, string>> = {
  en: {
    shortlist: 'Shortlist',
    reject: 'Reject',
    schedule_interview: 'Schedule interview',
    hire: 'Hire',
    notify: 'Contact candidate',
    send_assessment: 'Send assessment',
    send_video_interview: 'Send video interview',
    preview_cv: 'Preview CV',
    download_cv: 'Download CV',
    generate_evaluation: 'Generate analysis',
    mark_completed: 'Mark completed',
    mark_no_show: 'Mark no-show',
    cancel_interview: 'Cancel interview',
    write_notes: 'Write notes',
    open_candidate: 'Open candidate',
  },
  ar: {
    shortlist: 'إضافة للقائمة المختصرة',
    reject: 'رفض',
    schedule_interview: 'جدولة مقابلة',
    hire: 'تعيين',
    notify: 'التواصل مع المرشح',
    send_assessment: 'إرسال التقييم',
    send_video_interview: 'إرسال مقابلة فيديو',
    preview_cv: 'معاينة السيرة الذاتية',
    download_cv: 'تنزيل السيرة الذاتية',
    generate_evaluation: 'إنشاء التحليل',
    mark_completed: 'تحديد كمكتملة',
    mark_no_show: 'تسجيل عدم الحضور',
    cancel_interview: 'إلغاء المقابلة',
    write_notes: 'كتابة الملاحظات',
    open_candidate: 'فتح ملف المرشح',
  },
}

const COPY = {
  en: {
    language: 'العربية',
    candidateList: 'Candidate list',
    candidateListDescription: 'The real application stage, contact state, and next HR action for every candidate.',
    candidate: 'Candidate',
    job: 'Job',
    entryMethod: 'Entry method',
    applicationStage: 'Application stage',
    cvProcessing: 'CV processing',
    screening: 'Screening',
    communication: 'Communication',
    nextHumanAction: 'Next human action',
    automaticActions: 'Automatic actions',
    waitingForHr: 'Waiting for HR',
    operatorActions: 'Operator actions',
    candidateFacts: 'Verified facts',
    sourceEvidence: 'Source evidence',
    analysis: 'OctoHR analysis',
    recommendation: 'Recommendation',
    concerns: 'Concerns',
    missingInformation: 'Missing information',
    confidence: 'Confidence',
    humanDecision: 'Human decision',
    advisory: 'Advisory only. A human operator remains responsible for every decision.',
    notInformed: 'Stage changed — candidate has not been informed',
    noAutomaticActions: 'No automatic action is recorded yet.',
    noPendingHr: 'No HR action is currently waiting.',
    noPermittedActions: 'No actions are permitted for your current role and application stage.',
    interviewQueue: 'Interview queue',
    interviewQueueDescription: 'Interview status is shown separately from the candidate’s application stage.',
    interviewStatus: 'Interview status',
    interviewAgenda: 'This week',
    interviewAgendaDescription: 'A practical week agenda for live interviews. OctoHR owns the schedule.',
    interviewTabUpcoming: 'Upcoming',
    interviewTabVideo: 'Video',
    interviewTabNeedsFeedback: 'Needs feedback',
    interviewTabCompleted: 'Completed',
    interviewTabNoShow: 'No-shows',
    interviewTabCancelled: 'Cancelled',
    interviewTabAll: 'All',
    interviewMore: 'More',
    interviewFilters: 'Filters',
    interviewClearFilters: 'Clear filters',
    interviewUpdating: 'Updating…',
    interviewClose: 'Close',
    interviewInviteDetails: 'Invite details',
    interviewSentMessage: 'Sent message',
    interviewTimeline: 'Timeline',
    interviewStatusDetails: 'Status details',
    interviewState: 'Interview state',
    interviewFeedbackState: 'Feedback state',
    interviewLatestActivity: 'Latest activity',
    interviewScheduledTime: 'Scheduled time',
    interviewCreated: 'Created',
    interviewUpdated: 'Updated',
    interviewNotRecorded: 'Not recorded',
    interviewInvite: 'Invite',
    interviewMeeting: 'Meeting',
    interviewInviteSentAt: 'Invite sent at',
    interviewContact: 'Contact',
    interviewChannel: 'Channel',
    interviewVideoLink: 'Video interview link',
    interviewMeetAvailable: 'Meet link available',
    interviewLatestHrNotes: 'Latest HR notes',
    interviewFeedbackPlaceholder: 'Add interview feedback or next-step notes…',
    interviewSaveFeedback: 'Save feedback',
    interviewWaitingVideo: 'Waiting for the candidate to submit a video answer.',
    interviewReadyReview: 'The video answer is ready for HR review.',
    interviewReviewed: 'This video interview has been reviewed.',
    interviewCompletedFeedbackDone: 'Interview completed and feedback is complete.',
    interviewCompletedFeedbackPending: 'Interview completed. Feedback is pending.',
    interviewSetDatetime: 'Set a date and time for this interview.',
    interviewRecordedDefault: 'Recorded video interview.',
    interviewLiveType: 'Live interview',
    interviewFailedInvite: 'Invitation delivery failed. Resend when ready.',
    interviewVideoEvidence: 'Video interview evidence',
    interviewTryAgain: 'Try again',
    interviewQuestionList: 'Question list',
    interviewAnsweredFullList: 'Candidate answered the full question list in one video.',
    interviewVideoAnswer: 'Video answer',
    interviewQuestionN: 'Question {n}',
    interviewTranscript: 'Transcript',
    interviewTranscriptFailed: 'We could not prepare the written summary. The original video is still available for review.',
    interviewNoVideoAnswers: 'No video answers have been submitted yet.',
    interviewOverallImpression: 'Overall impression',
    interviewKeyStrengths: 'Key strengths',
    interviewFollowUpQuestions: 'Follow-up questions',
    interviewDetailedEvidence: 'Detailed evidence',
    interviewRoleFitEvidence: 'Role-fit evidence',
    interviewCommunicationNotes: 'Communication notes',
    interviewNoAiSummary: 'No AI summary is ready yet.',
    interviewReviewEvidenceNext: 'Review the available evidence and choose the next hiring step.',
    interviewNeedsMoreEvidence: 'Needs more evidence',
    interviewConfidenceLimited: 'Limited',
    interviewInterviewerPlaceholder: 'Interviewer',
    interviewDateFilter: 'Date',
    interviewFeedbackComplete: 'Complete',
    interviewFeedbackPending: 'Pending',
    interviewFeedbackNotStarted: 'Not started',
    interviewUnassigned: 'Unassigned',
    interviewMetricUpcoming: 'Upcoming interviews',
    interviewMetricCompleted: 'Completed',
    interviewMetricNoShows: 'No-shows',
    interviewMetricNeedFeedback: 'Need feedback',
    interviewMetricVideo: 'Video interviews',
    interviewMetricFeedbackComplete: 'Feedback complete',
    interviewSearchPlaceholder: 'Search candidate or email',
    interviewRolePlaceholder: 'Filter by role',
    interviewPanelPlaceholder: 'Panel / interviewer',
    interviewSearch: 'Search',
    interviewEmpty: 'No interviews match this queue. Try another tab or clear the filters.',
    interviewLoadError: 'Could not load interviews',
    interviewLoadErrorDetail: 'The interviews request failed. This is not an empty queue — try again.',
    interviewLoading: 'Loading interviews…',
    overviewWorkLoadError: 'Could not load your work',
    overviewWorkLoadErrorDetail: 'The work queue request failed. This is not an empty list — try again.',
    overviewWorkLoading: 'Loading your work…',
    interviewShowing: 'Showing {from}-{to} of {total}',
    interviewPrevious: 'Previous',
    interviewNext: 'Next',
    interviewNotesNotScorecard:
      'Free-text notes are not scorecards. Submit structured feedback separately.',
    interviewSyncStatus: 'Calendar sync',
    interviewProviderAccepted: 'Provider accepted',
    interviewDeliveredProven: 'Delivered (proven)',
    schedule: 'Date and time',
    channelLocation: 'Channel or location',
    invitationStatus: 'Invitation status',
    candidateConfirmation: 'Candidate confirmation',
    notesStatus: 'Notes status',
    aiSummary: 'OctoHR analysis',
    noAdvisoryAnalysis: 'No advisory analysis is available yet.',
    dateNotSet: 'Date and time not set',
    recordedVideo: 'Recorded video',
    open: 'Open',
    candidateContacted: 'Candidate contacted',
    currentStage: 'Current stage',
    // Overview / Control Center
    overviewNextAction: 'Suggested next action',
    overviewOpenWorkQueue: 'Open work queue',
    overviewOpenFollowUps: 'Open follow-ups',
    overviewOpenReady: 'Review candidates',
    overviewOpenAssessments: 'Open assessments',
    overviewOpenRoleRanking: 'Open role ranking',
    overviewCheckRanking: 'Check ranking',
    overviewNeedsAttention: 'What needs attention today',
    overviewNeedsAttentionDescription: 'Start with the hiring actions that move candidates forward.',
    overviewReviewReady: 'Review ready candidates',
    overviewReviewReadyDetailOne: '1 candidate ready for an HR decision.',
    overviewReviewReadyDetail: '{count} candidates ready for an HR decision.',
    overviewReviewReadyEmpty: 'No candidates are waiting for HR review.',
    overviewSendAssessments: 'Send assessments',
    overviewSendAssessmentsDetailOne: '1 candidate is ready for a first assessment send.',
    overviewSendAssessmentsDetail: '{count} candidates are ready for a first assessment send.',
    overviewSendAssessmentsEmpty: 'No candidates are ready for a first assessment send.',
    overviewResendAssessments: 'Resend expired assessments',
    overviewResendAssessmentsDetailOne: '1 candidate needs an assessment resend.',
    overviewResendAssessmentsDetail: '{count} candidates need an assessment resend.',
    overviewResendAssessmentsEmpty: 'No expired assessments need resend.',
    overviewDeliveryFailedAssessments: 'Review delivery failures',
    overviewDeliveryFailedAssessmentsDetailOne: '1 assessment invitation failed to deliver.',
    overviewDeliveryFailedAssessmentsDetail: '{count} assessment invitations failed to deliver.',
    overviewDeliveryFailedAssessmentsEmpty: 'No assessment delivery failures.',
    overviewInProgressAssessments: 'View in-progress assessments',
    overviewInProgressAssessmentsDetailOne: '1 candidate has an assessment in progress.',
    overviewInProgressAssessmentsDetail: '{count} candidates have assessments in progress.',
    overviewInProgressAssessmentsEmpty: 'No assessments are in progress.',
    overviewSentPendingAssessments: 'View sent assessments',
    overviewSentPendingAssessmentsDetailOne: '1 assessment is sent and waiting.',
    overviewSentPendingAssessmentsDetail: '{count} assessments are sent and waiting.',
    overviewSentPendingAssessmentsEmpty: 'No sent assessments are waiting.',
    overviewFollowUp: 'Follow up with candidates',
    overviewFollowUpDetailOne: '1 candidate needs HR follow-up.',
    overviewFollowUpDetail: '{count} candidates need HR follow-up.',
    overviewFollowUpEmpty: 'No candidate follow-ups need attention.',
    overviewPrioritizeRole: 'Prioritize by role',
    overviewPrioritizeRoleEmpty: 'No role needs priority attention right now.',
    overviewPriorityQueue: 'Priority queue',
    overviewPriorityQueueDescription: 'Specific people to contact or decide on next.',
    overviewTopPriorities: 'Top priorities',
    overviewViewAll: 'View all',
    overviewShowLess: 'Show less',
    overviewQueueCount: '{count} candidates',
    overviewQueueCountOne: '1 candidate',
    overviewRoleNextSteps: 'Role next steps',
    overviewRoleNextStepsDescription: 'What each opening needs from HR next.',
    overviewEmptyQueue: 'No urgent hiring actions right now.',
    overviewNoRoles: 'No active roles to analyze yet.',
    overviewPeopleUnit: 'people',
    overviewPeopleUnitOne: 'person',
    overviewApplicationsHint: '{count} applications',
    overviewWorkQueueShownTotal: '{shown} shown · {total} people',
    overviewActionsHint: '{count} actions',
    overviewRolePeopleActive: '{count} candidates',
    overviewRolePeopleActiveOne: '1 candidate',
    overviewBadgeFollowUp: 'Follow up',
    overviewBadgeReady: 'Ready',
    overviewBadgeAssessment: 'Assessment',
    overviewBadgeInterview: 'Interview',
    overviewBadgeRole: 'Role',
    overviewHeroFollowUpReason: '{count} candidates could not be reached. The oldest has been waiting {days} days.',
    overviewHeroFollowUpReasonOne: '1 candidate could not be reached and still needs a follow-up.',
    overviewHeroReadyReason: '{count} candidates are waiting for an HR decision.',
    overviewHeroReadyReasonOne: '1 candidate is waiting for an HR decision.',
    overviewHeroAssessmentReason: '{count} candidates are waiting for an assessment to be sent.',
    overviewHeroAssessmentReasonOne: '1 candidate is waiting for an assessment to be sent.',
    overviewHeroInterviewReason: '{count} candidates still need interview scheduling.',
    overviewHeroInterviewReasonOne: '1 candidate still needs interview scheduling.',
    overviewQueueFollowUp: 'Could not reach this candidate — follow up on another channel.',
    overviewQueueReady: 'Ready for an HR decision.',
    overviewQueueAssessment: 'Assessment action is still needed.',
    overviewQueueInterview: 'Interview scheduling is still needed.',
    overviewScheduleInterviews: 'Schedule interviews',
    overviewPageTitle: 'OctoHR Pre-Hiring Control Center',
    overviewPageSubtitle: 'A clean view of who needs review, who needs follow-up, and what HR should do next.',
    overviewEmptyHeroTitle: 'You’re caught up',
    overviewEmptyHeroReason: 'No open roles need attention, and there are no candidates waiting for review, follow-up, or assessment.',
    overviewRoleActiveCount: '{count} active',
    overviewRoleNoApplicants: 'No applicants yet. Share the QR or application link.',
    overviewRoleOpenList: 'Open the candidate list and decide who needs review first.',
    overviewRoleNoUrgent: 'No urgent action for this opening right now.',
    overviewRoleHelpScreeningOne: 'Help 1 candidate finish screening.',
    overviewRoleHelpScreening: 'Help {count} candidates finish screening.',
    overviewRoleReviewOne: 'Review 1 candidate and decide who moves forward.',
    overviewRoleReview: 'Review {count} candidates and decide who moves forward.',
    overviewRolePlanInterviewAssessmentOne: 'Plan interviews or assessments for 1 shortlisted candidate.',
    overviewRolePlanInterviewAssessment: 'Plan interviews or assessments for {count} shortlisted candidates.',
    overviewRolePlanInterviewOne: 'Plan interviews for 1 shortlisted candidate.',
    overviewRolePlanInterview: 'Plan interviews for {count} shortlisted candidates.',
    overviewRoleMoveForwardOne: 'Open this role and move 1 candidate forward.',
    overviewRoleMoveForward: 'Open this role and move {count} candidates forward.',
    jobsPageTitle: 'Jobs',
    jobsPageSubtitle: 'Create, edit, and manage job openings directly, with APPLY links and QR codes.',
    jobsOpeningsList: 'Job openings',
    jobsInventoryHint: 'Find an opening, then manage it or open its candidates.',
    jobsDone: 'Done',
    jobsOwnershipOptional: 'Ownership (optional)',
    jobsOwnershipHint: 'Search by name — Unassigned allowed',
    jobsCreate: 'Create job',
    jobsCreateAssistant: 'Draft with Assistant',
    jobsRefresh: 'Refresh',
    jobsExport: 'Export',
    jobsOpen: 'Open',
    jobsDraft: 'Draft',
    jobsPaused: 'Paused',
    jobsClosed: 'Closed',
    jobsApplications: 'Total applications',
    jobsOpenRoles: 'Open roles',
    jobsSearchPlaceholder: 'Search jobs by title or code…',
    jobsFilterStatus: 'Status',
    jobsFilterAll: 'All',
    jobsFilterDepartment: 'Department',
    jobsFilterLocation: 'Location',
    jobsFilterRemaining: 'Has remaining vacancies',
    jobsFilterDeadline: 'Deadline',
    jobsDeadlineAny: 'Any',
    jobsDeadlineUpcoming: 'Upcoming',
    jobsDeadlineOverdue: 'Overdue',
    jobsDeadlineNone: 'None',
    jobsMoreFilters: 'More filters',
    jobsHideFilters: 'Hide filters',
    jobsClearFilters: 'Clear filters',
    jobsShowing: 'Showing {loaded} of {total} openings',
    jobsLoadMore: 'Load more',
    jobsLoadingLabel: 'Loading…',
    jobsResultCount: '{count} result(s) for “{query}”',
    jobsEmptyFiltered: 'No openings match these filters.',
    jobsAppsOne: '1 application',
    jobsAppsMany: '{count} applications',
    jobsNoAppsYet: 'No applications yet',
    jobsDeadlineOverdueLabel: 'Deadline overdue',
    jobsAssigned: 'Assigned',
    jobsCreateDisabled: 'Creating job openings is disabled for your role',
    jobsOpenRowAria: 'Manage {title}',
    jobsViewCandidatesAria: 'View candidates for {title}',
    jobsColJob: 'Job',
    jobsColCode: 'APPLY code',
    jobsColStatus: 'Status',
    jobsColVacancies: 'Vacancies',
    jobsColCapacity: 'Capacity',
    jobsColApps: 'Applications',
    jobsColOwner: 'Owner',
    jobsColDeadline: 'Deadline',
    jobsColAge: 'Age',
    jobsColAction: 'Action',
    jobsColOpen: 'Open',
    jobsManage: 'Manage',
    jobsEdit: 'Edit',
    jobsEmpty: 'No job openings yet. Create a job to save a draft or publish.',
    jobsEmptySearch: 'No job openings match “{query}”.',
    jobsFormCreateTitle: 'Create job',
    jobsFormEditTitle: 'Edit job',
    jobsFormSubtitle: 'Save as draft or publish when ready. Editing never silently changes status.',
    jobsCancel: 'Cancel',
    jobsSaveDraft: 'Save draft',
    jobsSaveChanges: 'Save changes',
    jobsPublish: 'Publish job',
    jobsPreview: 'Preview',
    jobsHidePreview: 'Hide preview',
    jobsUnsavedConfirm: 'You have unsaved changes. Leave this form?',
    jobsFieldTitleEn: 'English title',
    jobsFieldTitleAr: 'Arabic title',
    jobsFieldVisibility: 'Candidate visibility',
    jobsVisibilityPublic: 'Public — discoverable and shareable',
    jobsVisibilityShareOnly: 'Share only — exact APPLY link or QR',
    jobsVisibilityInternal: 'Internal — never available on candidate WhatsApp',
    jobsFieldSummaryEn: 'Candidate summary in English',
    jobsFieldSummaryAr: 'Candidate summary in Arabic',
    jobsApproveContentEn: 'I approve the English candidate-facing content',
    jobsApproveContentAr: 'I approve the Arabic candidate-facing content',
    jobsFieldCode: 'Position code',
    jobsFieldCodeHint: 'Auto-generated if blank',
    jobsFieldDepartment: 'Department',
    jobsFieldLocation: 'Location / branch',
    jobsFieldEmploymentType: 'Employment type',
    jobsFieldWorkArrangement: 'Work arrangement',
    jobsFieldContractType: 'Contract type',
    jobsFieldSalaryMin: 'Salary minimum',
    jobsFieldSalaryMax: 'Salary maximum',
    jobsFieldCurrency: 'Currency',
    jobsFieldSalaryVisibility: 'Salary visibility',
    jobsSalaryHrOnly: 'HR only',
    jobsSalaryPublic: 'Public',
    jobsFieldVacancies: 'Approved vacancies',
    jobsFieldDeadline: 'Application deadline',
    jobsFieldStartDate: 'Expected start date',
    jobsFieldRecruiter: 'Recruiter user ID',
    jobsFieldHiringManager: 'Hiring manager user ID',
    jobsFieldDescriptionEn: 'English description',
    jobsFieldDescriptionAr: 'Arabic description',
    jobsFieldRequirementsEn: 'English requirements (one per line)',
    jobsFieldRequirementsAr: 'Arabic requirements (one per line)',
    jobsValidationTitleRequired: 'An English or Arabic title is required.',
    jobsValidationNumber: 'Enter a valid number.',
    jobsValidationVacancies: 'Publishing requires at least one vacancy.',
    jobsValidationSalaryRange: 'Maximum salary must be greater than or equal to minimum.',
    jobsValidationLocationRemote: 'Add a location or select a fully remote work arrangement.',
    jobsValidationEmploymentType: 'Employment type is required to publish.',
    jobsValidationApprovedContent: 'Approve one complete language pack: title, candidate summary, and at least one requirement.',
    jobsValidationPublicSalary: 'Public salary requires minimum, maximum, and currency.',
    jobsPreviewUntitled: 'Untitled job',
    jobsPreviewNoDescription: 'No description yet.',
    jobsClose: 'Close job',
    jobsReopen: 'Reopen job',
    jobsPause: 'Pause job',
    jobsResume: 'Resume job',
    jobsPublishConfirm: 'Publish this job and accept applications?',
    jobsPublishConfirmBody: 'Publishing makes this opening accept APPLY intake. You can pause or close it later.',
    jobsPauseConfirm: 'Pause this job so it stops accepting new applications?',
    jobsPauseConfirmBody: 'Temporary: intake stops until you resume. Existing candidates stay in the pipeline.',
    jobsCloseConfirm: 'Close this job to new applications? Existing candidates stay in the pipeline.',
    jobsCloseConfirmBody: 'Closing ends intake for this opening. You can reopen later if needed.',
    jobsCloseConfirmActive: '{count} active candidate(s) remain in the pipeline.',
    jobsReopenConfirm: 'Reopen this job to accept applications again?',
    jobsReopenConfirmBody: 'APPLY intake will start again for this opening.',
    jobsResumeConfirm: 'Resume this paused job?',
    jobsResumeConfirmBody: 'APPLY intake will start again until you pause or close it.',
    jobsRemaining: '{remaining} remaining of {total}',
    jobsAgeDays: '{days}d',
    jobsIntakeOpen: 'Accepting applications',
    jobsIntakeClosed: 'Not accepting applications',
    jobsShareUnavailable: 'External sharing is unavailable for this job.',
    jobsShareReady: 'Ready to share with candidates',
    jobsEligibilityReason: 'Intake status',
    jobsEligibility_job_not_accepting: 'Not accepting applications',
    jobsEligibility_job_paused: 'Paused — not accepting applications',
    jobsEligibility_job_closed: 'Closed — not accepting applications',
    jobsEligibility_job_deadline_passed: 'Application deadline has passed',
    jobsEligibility_job_vacancies_exhausted: 'No remaining vacancies',
    jobsEligibility_job_visibility_denied: 'Internal only — not available on candidate WhatsApp',
    jobsEligibility_job_content_incomplete: 'Candidate-facing content is incomplete or unapproved',
    jobsEligibility_unknown: 'Not available for candidate sharing',
    jobsApplicationLinkUnavailable: 'Not available for sharing',
    jobsApplyCodeInternal: 'Internal identity (not for candidate sharing)',
    jobsWsTabs: 'Job workspace',
    jobsWsTabOverview: 'Overview',
    jobsWsTabSharing: 'Sharing',
    jobsWsTabApplicants: 'Applicants',
    jobsWsTabActivity: 'Activity',
    jobsWsKeyFacts: 'Key job facts',
    jobsWsOverviewFactsHint: 'Only the useful, current job details are shown by default.',
    jobsWsCandidateFacing: 'Candidate-facing content',
    jobsWsOverviewDescHint: 'What candidates see for this opening.',
    jobsWsRequirements: 'Requirements',
    jobsWsNoRequirements: 'No structured requirements are stored for this opening yet.',
    jobsWsSharingHint: 'Everything needed to share this job with candidates.',
    jobsWsShareCard: 'Share with candidates',
    jobsWsApplyLink: 'Application link',
    jobsWsCopyCode: 'Copy code',
    jobsWsCopyLink: 'Copy link',
    jobsWsOpenLink: 'Copy link again',
    jobsWsQr: 'QR code',
    jobsWsQrHint: 'Use this on print, flyers, or in-person intake.',
    jobsWsQrNotReady: 'QR link is not available for this job yet.',
    jobsWsDownloadQr: 'Download QR',
    jobsWsFunnel: 'Candidate funnel by stage',
    jobsWsFunnelHint: 'How applicants for this job move through stages.',
    jobsWsNoStageActivity: 'No applicants have entered this funnel yet.',
    jobsWsViewCandidates: 'View candidates',
    jobsWsRecentApplicants: 'Recent applicants',
    jobsWsRecentHint: 'Latest people who applied to this job.',
    jobsWsNoApplicants: 'No applicants have used this job link yet.',
    jobsWsCandidateActivity: 'Candidate contact activity',
    jobsWsActivityHint: 'Recent candidate contact attempts tied to this opening.',
    jobsWsNoActivity: 'No recent candidate contact activity for this opening.',
    jobsWsCandidateContact: 'Candidate contact',
    jobsFormDirty: 'Unsaved changes',
    jobsFormClean: 'All changes saved',
    jobsFormSectionBasics: 'Basics',
    jobsFormSectionBasicsHint: 'Name, code, and visibility.',
    jobsFormSectionHiring: 'Hiring setup',
    jobsFormSectionHiringHint: 'Department, location, schedule, and vacancies.',
    jobsFormSectionContent: 'Candidate-facing content',
    jobsFormSectionContentHint: 'What candidates see in English and Arabic.',
    jobsFormSectionAdvanced: 'Advanced / optional',
    jobsFormSectionAdvancedHint: 'Contract, salary, and internal ownership.',
    jobsCloseWorkspace: 'Close',
  },
  ar: {
    language: 'English',
    candidateList: 'قائمة المرشحين',
    candidateListDescription: 'المرحلة الفعلية للطلب وحالة التواصل والخطوة التالية للموارد البشرية.',
    candidate: 'المرشح',
    job: 'الوظيفة',
    entryMethod: 'طريقة الدخول',
    applicationStage: 'مرحلة الطلب',
    cvProcessing: 'معالجة السيرة الذاتية',
    screening: 'الفرز',
    communication: 'حالة التواصل',
    nextHumanAction: 'الإجراء البشري التالي',
    automaticActions: 'الإجراءات التلقائية',
    waitingForHr: 'بانتظار الموارد البشرية',
    operatorActions: 'إجراءات المشغّل',
    candidateFacts: 'حقائق موثّقة',
    sourceEvidence: 'أدلة المصدر',
    analysis: 'تحليل OctoHR',
    recommendation: 'التوصية',
    concerns: 'المخاوف',
    missingInformation: 'المعلومات الناقصة',
    confidence: 'مستوى الثقة',
    humanDecision: 'القرار البشري',
    advisory: 'للاستشارة فقط. يبقى المشغّل البشري مسؤولاً عن كل قرار.',
    notInformed: 'تغيّرت المرحلة — لم يتم إبلاغ المرشح',
    noAutomaticActions: 'لم يتم تسجيل إجراء تلقائي حتى الآن.',
    noPendingHr: 'لا يوجد إجراء معلّق للموارد البشرية حالياً.',
    noPermittedActions: 'لا توجد إجراءات مسموحة لدورك ومرحلة الطلب الحالية.',
    interviewQueue: 'قائمة المقابلات',
    interviewQueueDescription: 'تُعرض حالة المقابلة بشكل منفصل عن مرحلة طلب المرشح.',
    interviewStatus: 'حالة المقابلة',
    interviewAgenda: 'هذا الأسبوع',
    interviewAgendaDescription: 'أجندة أسبوعية عملية للمقابلات المباشرة. يملك OctoHR الجدولة.',
    interviewTabUpcoming: 'القادمة',
    interviewTabVideo: 'فيديو',
    interviewTabNeedsFeedback: 'تحتاج ملاحظات',
    interviewTabCompleted: 'مكتملة',
    interviewTabNoShow: 'عدم حضور',
    interviewTabCancelled: 'ملغاة',
    interviewTabAll: 'الكل',
    interviewMore: 'المزيد',
    interviewFilters: 'تصفية',
    interviewClearFilters: 'مسح التصفية',
    interviewUpdating: 'جاري التحديث…',
    interviewClose: 'إغلاق',
    interviewInviteDetails: 'تفاصيل الدعوة',
    interviewSentMessage: 'الرسالة المرسلة',
    interviewTimeline: 'الجدول الزمني',
    interviewStatusDetails: 'تفاصيل الحالة',
    interviewState: 'حالة المقابلة',
    interviewFeedbackState: 'حالة التقييم',
    interviewLatestActivity: 'آخر نشاط',
    interviewScheduledTime: 'الوقت المحدد',
    interviewCreated: 'أُنشئت',
    interviewUpdated: 'آخر تحديث',
    interviewNotRecorded: 'غير مسجّل',
    interviewInvite: 'الدعوة',
    interviewMeeting: 'الاجتماع',
    interviewInviteSentAt: 'وقت إرسال الدعوة',
    interviewContact: 'جهة الاتصال',
    interviewChannel: 'القناة',
    interviewVideoLink: 'رابط مقابلة الفيديو',
    interviewMeetAvailable: 'رابط الاجتماع متاح',
    interviewLatestHrNotes: 'أحدث ملاحظات الموارد البشرية',
    interviewFeedbackPlaceholder: 'أضف ملاحظات المقابلة أو الخطوات التالية…',
    interviewSaveFeedback: 'حفظ الملاحظات',
    interviewWaitingVideo: 'بانتظار تقديم المرشح لإجابة فيديو.',
    interviewReadyReview: 'إجابة الفيديو جاهزة لمراجعة الموارد البشرية.',
    interviewReviewed: 'تمت مراجعة مقابلة الفيديو.',
    interviewCompletedFeedbackDone: 'اكتملت المقابلة والتقييم.',
    interviewCompletedFeedbackPending: 'اكتملت المقابلة. التقييم معلّق.',
    interviewSetDatetime: 'حدّد تاريخاً ووقتاً لهذه المقابلة.',
    interviewRecordedDefault: 'مقابلة فيديو مسجّلة.',
    interviewLiveType: 'مقابلة مباشرة',
    interviewFailedInvite: 'فشل تسليم الدعوة. أعد الإرسال عند الجاهزية.',
    interviewVideoEvidence: 'أدلة مقابلة الفيديو',
    interviewTryAgain: 'إعادة المحاولة',
    interviewQuestionList: 'قائمة الأسئلة',
    interviewAnsweredFullList: 'أجاب المرشح على قائمة الأسئلة كاملة في فيديو واحد.',
    interviewVideoAnswer: 'إجابة الفيديو',
    interviewQuestionN: 'السؤال {n}',
    interviewTranscript: 'النص',
    interviewTranscriptFailed: 'تعذر إعداد الملخص المكتوب. الفيديو الأصلي ما زال متاحاً للمراجعة.',
    interviewNoVideoAnswers: 'لم تُقدَّم إجابات فيديو بعد.',
    interviewOverallImpression: 'الانطباع العام',
    interviewKeyStrengths: 'نقاط القوة',
    interviewFollowUpQuestions: 'أسئلة المتابعة',
    interviewDetailedEvidence: 'أدلة تفصيلية',
    interviewRoleFitEvidence: 'أدلة ملاءمة الدور',
    interviewCommunicationNotes: 'ملاحظات التواصل',
    interviewNoAiSummary: 'لا يتوفر ملخص ذكي بعد.',
    interviewReviewEvidenceNext: 'راجع الأدلة المتاحة واختر خطوة التوظيف التالية.',
    interviewNeedsMoreEvidence: 'يحتاج المزيد من الأدلة',
    interviewConfidenceLimited: 'محدود',
    interviewInterviewerPlaceholder: 'المقابِل',
    interviewDateFilter: 'التاريخ',
    interviewFeedbackComplete: 'مكتمل',
    interviewFeedbackPending: 'معلّق',
    interviewFeedbackNotStarted: 'لم يبدأ',
    interviewUnassigned: 'غير معيّن',
    interviewMetricUpcoming: 'مقابلات قادمة',
    interviewMetricCompleted: 'مكتملة',
    interviewMetricNoShows: 'عدم حضور',
    interviewMetricNeedFeedback: 'تحتاج ملاحظات',
    interviewMetricVideo: 'مقابلات الفيديو',
    interviewMetricFeedbackComplete: 'ملاحظات مكتملة',
    interviewSearchPlaceholder: 'ابحث عن مرشح أو بريد',
    interviewRolePlaceholder: 'تصفية حسب الوظيفة',
    interviewPanelPlaceholder: 'اللجنة / المقابل',
    interviewSearch: 'بحث',
    interviewEmpty: 'لا توجد مقابلات مطابقة. جرّب تبويباً آخر أو امسح عوامل التصفية.',
    interviewLoadError: 'تعذّر تحميل المقابلات',
    interviewLoadErrorDetail: 'فشل طلب المقابلات. هذه ليست قائمة فارغة — حاول مرة أخرى.',
    interviewLoading: 'جاري تحميل المقابلات…',
    overviewWorkLoadError: 'تعذّر تحميل عملك',
    overviewWorkLoadErrorDetail: 'فشل طلب قائمة العمل. هذه ليست قائمة فارغة — حاول مرة أخرى.',
    overviewWorkLoading: 'جاري تحميل عملك…',
    interviewShowing: 'عرض {from}-{to} من {total}',
    interviewPrevious: 'السابق',
    interviewNext: 'التالي',
    interviewNotesNotScorecard: 'الملاحظات النصية ليست بطاقة تقييم. أرسل الملاحظات المنظمة بشكل منفصل.',
    interviewSyncStatus: 'مزامنة التقويم',
    interviewProviderAccepted: 'قبول المزوّد',
    interviewDeliveredProven: 'تم التسليم (مثبت)',
    schedule: 'التاريخ والوقت',
    channelLocation: 'القناة أو الموقع',
    invitationStatus: 'حالة الدعوة',
    candidateConfirmation: 'تأكيد المرشح',
    notesStatus: 'حالة الملاحظات',
    aiSummary: 'تحليل OctoHR',
    noAdvisoryAnalysis: 'لا يتوفر تحليل استشاري حتى الآن.',
    dateNotSet: 'لم يتم تحديد التاريخ والوقت',
    recordedVideo: 'فيديو مسجّل',
    open: 'فتح',
    candidateContacted: 'تم التواصل مع المرشح',
    currentStage: 'المرحلة الحالية',
    overviewNextAction: 'الإجراء التالي المقترح',
    overviewOpenWorkQueue: 'فتح قائمة العمل',
    overviewOpenFollowUps: 'فتح المتابعات',
    overviewOpenReady: 'مراجعة المرشحين',
    overviewOpenAssessments: 'فتح التقييمات',
    overviewOpenRoleRanking: 'فتح ترتيب الوظيفة',
    overviewCheckRanking: 'عرض الترتيب',
    overviewNeedsAttention: 'ما يحتاج انتباهك اليوم',
    overviewNeedsAttentionDescription: 'ابدأ بإجراءات التوظيف التي تحرّك المرشحين إلى الأمام.',
    overviewReviewReady: 'مراجعة المرشحين الجاهزين',
    overviewReviewReadyDetailOne: 'مرشح واحد جاهز لقرار الموارد البشرية.',
    overviewReviewReadyDetail: '{count} مرشحين جاهزين لقرار الموارد البشرية.',
    overviewReviewReadyEmpty: 'لا يوجد مرشحون بانتظار المراجعة.',
    overviewSendAssessments: 'إرسال التقييمات',
    overviewSendAssessmentsDetailOne: 'مرشح واحد جاهز لإرسال التقييم لأول مرة.',
    overviewSendAssessmentsDetail: '{count} مرشحين جاهزين لإرسال التقييم لأول مرة.',
    overviewSendAssessmentsEmpty: 'لا يوجد مرشحون جاهزون لإرسال التقييم لأول مرة.',
    overviewResendAssessments: 'إعادة إرسال التقييمات المنتهية',
    overviewResendAssessmentsDetailOne: 'مرشح واحد يحتاج إعادة إرسال التقييم.',
    overviewResendAssessmentsDetail: '{count} مرشحين يحتاجون إعادة إرسال التقييم.',
    overviewResendAssessmentsEmpty: 'لا توجد تقييمات منتهية تحتاج إعادة إرسال.',
    overviewDeliveryFailedAssessments: 'مراجعة فشل التسليم',
    overviewDeliveryFailedAssessmentsDetailOne: 'دعوة تقييم واحدة فشلت في التسليم.',
    overviewDeliveryFailedAssessmentsDetail: '{count} دعوات تقييم فشلت في التسليم.',
    overviewDeliveryFailedAssessmentsEmpty: 'لا توجد حالات فشل لتسليم التقييم.',
    overviewInProgressAssessments: 'عرض التقييمات الجارية',
    overviewInProgressAssessmentsDetailOne: 'مرشح واحد لديه تقييم قيد التنفيذ.',
    overviewInProgressAssessmentsDetail: '{count} مرشحين لديهم تقييمات قيد التنفيذ.',
    overviewInProgressAssessmentsEmpty: 'لا توجد تقييمات قيد التنفيذ.',
    overviewSentPendingAssessments: 'عرض التقييمات المُرسلة',
    overviewSentPendingAssessmentsDetailOne: 'تقييم واحد مُرسل وبانتظار البدء.',
    overviewSentPendingAssessmentsDetail: '{count} تقييمات مُرسلة وبانتظار البدء.',
    overviewSentPendingAssessmentsEmpty: 'لا توجد تقييمات مُرسلة بانتظار البدء.',
    overviewFollowUp: 'متابعة المرشحين',
    overviewFollowUpDetailOne: 'مرشح واحد يحتاج متابعة من الموارد البشرية.',
    overviewFollowUpDetail: '{count} مرشحين يحتاجون متابعة من الموارد البشرية.',
    overviewFollowUpEmpty: 'لا توجد متابعات تحتاج انتباهًا.',
    overviewPrioritizeRole: 'أولوية حسب الوظيفة',
    overviewPrioritizeRoleEmpty: 'لا توجد وظيفة تحتاج أولوية الآن.',
    overviewPriorityQueue: 'قائمة الأولويات',
    overviewPriorityQueueDescription: 'أشخاص محددون للتواصل معهم أو اتخاذ قرار بشأنهم تاليًا.',
    overviewTopPriorities: 'أعلى الأولويات',
    overviewViewAll: 'عرض الكل',
    overviewShowLess: 'عرض أقل',
    overviewQueueCount: '{count} مرشحين',
    overviewQueueCountOne: 'مرشح واحد',
    overviewRoleNextSteps: 'الخطوات التالية للوظائف',
    overviewRoleNextStepsDescription: 'ما تحتاجه كل وظيفة من الموارد البشرية تاليًا.',
    overviewEmptyQueue: 'لا توجد إجراءات توظيف عاجلة الآن.',
    overviewNoRoles: 'لا توجد وظائف نشطة للتحليل بعد.',
    overviewPeopleUnit: 'أشخاص',
    overviewPeopleUnitOne: 'شخص',
    overviewApplicationsHint: '{count} طلبات',
    overviewWorkQueueShownTotal: '{shown} معروضة · {total} أشخاص',
    overviewActionsHint: '{count} إجراءات',
    overviewRolePeopleActive: '{count} مرشحين',
    overviewRolePeopleActiveOne: 'مرشح واحد',
    overviewBadgeFollowUp: 'متابعة',
    overviewBadgeReady: 'جاهز',
    overviewBadgeAssessment: 'تقييم',
    overviewBadgeInterview: 'مقابلة',
    overviewBadgeRole: 'وظيفة',
    overviewHeroFollowUpReason: 'تعذر الوصول إلى {count} مرشحين. أقدمهم بانتظار المتابعة منذ {days} يومًا.',
    overviewHeroFollowUpReasonOne: 'تعذر الوصول إلى مرشح واحد وما زال يحتاج متابعة.',
    overviewHeroReadyReason: '{count} مرشحين بانتظار قرار من الموارد البشرية.',
    overviewHeroReadyReasonOne: 'مرشح واحد بانتظار قرار من الموارد البشرية.',
    overviewHeroAssessmentReason: '{count} مرشحين بانتظار إرسال التقييم.',
    overviewHeroAssessmentReasonOne: 'مرشح واحد بانتظار إرسال التقييم.',
    overviewHeroInterviewReason: '{count} مرشحين ما زالوا يحتاجون جدولة مقابلة.',
    overviewHeroInterviewReasonOne: 'مرشح واحد ما زال يحتاج جدولة مقابلة.',
    overviewQueueFollowUp: 'تعذر الوصول إلى هذا المرشح — تابع عبر قناة أخرى.',
    overviewQueueReady: 'جاهز لقرار الموارد البشرية.',
    overviewQueueAssessment: 'ما زال إجراء التقييم مطلوبًا.',
    overviewQueueInterview: 'ما زالت جدولة المقابلة مطلوبة.',
    overviewScheduleInterviews: 'جدولة المقابلات',
    overviewPageTitle: 'مركز التحكم في التوظيف المسبق — OctoHR',
    overviewPageSubtitle: 'عرض واضح لمن يحتاج مراجعة أو متابعة، وما يجب على الموارد البشرية فعله تاليًا.',
    overviewEmptyHeroTitle: 'لا يوجد عمل معلّق الآن',
    overviewEmptyHeroReason: 'لا توجد وظائف مفتوحة تحتاج انتباهًا، ولا مرشحون بانتظار المراجعة أو المتابعة أو التقييم.',
    overviewRoleActiveCount: '{count} نشط',
    overviewRoleNoApplicants: 'لا يوجد متقدمون بعد. شارك رمز QR أو رابط التقديم.',
    overviewRoleOpenList: 'افتح قائمة المرشحين وقرر من يحتاج المراجعة أولًا.',
    overviewRoleNoUrgent: 'لا يوجد إجراء عاجل لهذه الوظيفة الآن.',
    overviewRoleHelpScreeningOne: 'ساعد مرشحًا واحدًا على إكمال الفرز.',
    overviewRoleHelpScreening: 'ساعد {count} مرشحين على إكمال الفرز.',
    overviewRoleReviewOne: 'راجع مرشحًا واحدًا وقرر من يتقدم.',
    overviewRoleReview: 'راجع {count} مرشحين وقرر من يتقدم.',
    overviewRolePlanInterviewAssessmentOne: 'خطّط لمقابلة أو تقييم لمرشح واحد في القائمة المختصرة.',
    overviewRolePlanInterviewAssessment: 'خطّط لمقابلات أو تقييمات لـ {count} مرشحين في القائمة المختصرة.',
    overviewRolePlanInterviewOne: 'خطّط لمقابلة لمرشح واحد في القائمة المختصرة.',
    overviewRolePlanInterview: 'خطّط لمقابلات لـ {count} مرشحين في القائمة المختصرة.',
    overviewRoleMoveForwardOne: 'افتح هذه الوظيفة وحرّك مرشحًا واحدًا إلى الأمام.',
    overviewRoleMoveForward: 'افتح هذه الوظيفة وحرّك {count} مرشحين إلى الأمام.',
    jobsPageTitle: 'الوظائف',
    jobsPageSubtitle: 'أنشئ وعدّل وأدر الوظائف مباشرة، مع روابط التقديم ورموز QR.',
    jobsOpeningsList: 'قائمة الوظائف',
    jobsInventoryHint: 'اعثر على وظيفة، ثم أدِرها أو افتح مرشحيها.',
    jobsDone: 'تم',
    jobsOwnershipOptional: 'الملكية (اختياري)',
    jobsOwnershipHint: 'ابحث بالاسم — يمكن الترك بدون إسناد',
    jobsCreate: 'إنشاء وظيفة',
    jobsCreateAssistant: 'إنشاء بمساعدة المساعد',
    jobsRefresh: 'تحديث',
    jobsExport: 'تصدير',
    jobsOpen: 'مفتوحة',
    jobsDraft: 'مسودة',
    jobsPaused: 'موقوفة مؤقتًا',
    jobsClosed: 'مغلقة',
    jobsApplications: 'إجمالي الطلبات',
    jobsOpenRoles: 'الوظائف المفتوحة',
    jobsSearchPlaceholder: 'ابحث بالعنوان أو الرمز…',
    jobsFilterStatus: 'الحالة',
    jobsFilterAll: 'الكل',
    jobsFilterDepartment: 'القسم',
    jobsFilterLocation: 'الموقع',
    jobsFilterRemaining: 'متبقي شواغر',
    jobsFilterDeadline: 'الموعد النهائي',
    jobsDeadlineAny: 'أي',
    jobsDeadlineUpcoming: 'قادم',
    jobsDeadlineOverdue: 'متأخر',
    jobsDeadlineNone: 'بدون موعد',
    jobsMoreFilters: 'مزيد من التصفية',
    jobsHideFilters: 'إخفاء التصفية',
    jobsClearFilters: 'مسح التصفية',
    jobsShowing: 'عرض {loaded} من {total} وظيفة',
    jobsLoadMore: 'تحميل المزيد',
    jobsLoadingLabel: 'جاري التحميل…',
    jobsResultCount: '{count} نتيجة لـ “{query}”',
    jobsEmptyFiltered: 'لا توجد وظائف تطابق هذه التصفية.',
    jobsAppsOne: 'طلب واحد',
    jobsAppsMany: '{count} طلبات',
    jobsNoAppsYet: 'لا طلبات بعد',
    jobsDeadlineOverdueLabel: 'الموعد النهائي متأخر',
    jobsAssigned: 'مسند',
    jobsCreateDisabled: 'إنشاء الوظائف غير متاح لدورك',
    jobsOpenRowAria: 'إدارة {title}',
    jobsViewCandidatesAria: 'عرض مرشحي {title}',
    jobsColJob: 'الوظيفة',
    jobsColCode: 'رمز التقديم',
    jobsColStatus: 'الحالة',
    jobsColVacancies: 'الشواغر',
    jobsColCapacity: 'السعة',
    jobsColApps: 'الطلبات',
    jobsColOwner: 'المسؤول',
    jobsColDeadline: 'الموعد النهائي',
    jobsColAge: 'العمر',
    jobsColAction: 'إجراء',
    jobsColOpen: 'فتح',
    jobsManage: 'إدارة',
    jobsEdit: 'تعديل',
    jobsEmpty: 'لا توجد وظائف بعد. أنشئ وظيفة لحفظ مسودة أو نشرها.',
    jobsEmptySearch: 'لا توجد وظائف تطابق “{query}”.',
    jobsFormCreateTitle: 'إنشاء وظيفة',
    jobsFormEditTitle: 'تعديل الوظيفة',
    jobsFormSubtitle: 'احفظ كمسودة أو انشر عند الجاهزية. التعديل لا يغيّر الحالة تلقائيًا.',
    jobsCancel: 'إلغاء',
    jobsSaveDraft: 'حفظ كمسودة',
    jobsSaveChanges: 'حفظ التغييرات',
    jobsPublish: 'نشر الوظيفة',
    jobsPreview: 'معاينة',
    jobsHidePreview: 'إخفاء المعاينة',
    jobsUnsavedConfirm: 'لديك تغييرات غير محفوظة. هل تريد المغادرة؟',
    jobsFieldTitleEn: 'المسمى بالإنجليزية',
    jobsFieldTitleAr: 'المسمى بالعربية',
    jobsFieldVisibility: 'ظهور الوظيفة للمرشحين',
    jobsVisibilityPublic: 'عام — قابل للاكتشاف والمشاركة',
    jobsVisibilityShareOnly: 'بالمشاركة فقط — عبر رمز APPLY أو QR',
    jobsVisibilityInternal: 'داخلي — غير متاح في واتساب المرشحين',
    jobsFieldSummaryEn: 'ملخص المرشح بالإنجليزية',
    jobsFieldSummaryAr: 'ملخص المرشح بالعربية',
    jobsApproveContentEn: 'أعتمد المحتوى الإنجليزي الظاهر للمرشح',
    jobsApproveContentAr: 'أعتمد المحتوى العربي الظاهر للمرشح',
    jobsFieldCode: 'رمز الوظيفة',
    jobsFieldCodeHint: 'يُولَّد تلقائيًا إن تُرك فارغًا',
    jobsFieldDepartment: 'القسم',
    jobsFieldLocation: 'الموقع / الفرع',
    jobsFieldEmploymentType: 'نوع التوظيف',
    jobsFieldWorkArrangement: 'نظام العمل',
    jobsFieldContractType: 'نوع العقد',
    jobsFieldSalaryMin: 'الحد الأدنى للراتب',
    jobsFieldSalaryMax: 'الحد الأعلى للراتب',
    jobsFieldCurrency: 'العملة',
    jobsFieldSalaryVisibility: 'ظهور الراتب',
    jobsSalaryHrOnly: 'للموارد البشرية فقط',
    jobsSalaryPublic: 'عام',
    jobsFieldVacancies: 'عدد الشواغر المعتمدة',
    jobsFieldDeadline: 'آخر موعد للتقديم',
    jobsFieldStartDate: 'تاريخ البدء المتوقع',
    jobsFieldRecruiter: 'معرّف مسؤول التوظيف',
    jobsFieldHiringManager: 'معرّف مدير التوظيف',
    jobsFieldDescriptionEn: 'الوصف بالإنجليزية',
    jobsFieldDescriptionAr: 'الوصف بالعربية',
    jobsFieldRequirementsEn: 'المتطلبات بالإنجليزية (سطر لكل بند)',
    jobsFieldRequirementsAr: 'المتطلبات بالعربية (سطر لكل بند)',
    jobsValidationTitleRequired: 'المسمى بالإنجليزية أو العربية مطلوب.',
    jobsValidationNumber: 'أدخل رقمًا صالحًا.',
    jobsValidationVacancies: 'يتطلب النشر شاغرًا واحدًا على الأقل.',
    jobsValidationSalaryRange: 'الحد الأعلى يجب أن يكون أكبر من أو يساوي الحد الأدنى.',
    jobsValidationLocationRemote: 'أضف موقعًا أو اختر نظام عمل عن بُعد بالكامل.',
    jobsValidationEmploymentType: 'نوع التوظيف مطلوب للنشر.',
    jobsValidationApprovedContent: 'اعتمد حزمة لغة مكتملة: المسمى والملخص ومتطلب واحد على الأقل.',
    jobsValidationPublicSalary: 'إظهار الراتب يتطلب الحد الأدنى والأعلى والعملة.',
    jobsPreviewUntitled: 'وظيفة بدون عنوان',
    jobsPreviewNoDescription: 'لا يوجد وصف بعد.',
    jobsClose: 'إغلاق الوظيفة',
    jobsReopen: 'إعادة الفتح',
    jobsPause: 'إيقاف مؤقت',
    jobsResume: 'استئناف',
    jobsPublishConfirm: 'نشر هذه الوظيفة وقبول الطلبات؟',
    jobsPublishConfirmBody: 'النشر يفتح استقبال طلبات APPLY. يمكن الإيقاف أو الإغلاق لاحقًا.',
    jobsPauseConfirm: 'إيقاف هذه الوظيفة مؤقتًا عن قبول طلبات جديدة؟',
    jobsPauseConfirmBody: 'مؤقت: يتوقف الاستقبال حتى الاستئناف. يبقى المرشحون الحاليون في المسار.',
    jobsCloseConfirm: 'إغلاق هذه الوظيفة نهائيًا عن الطلبات الجديدة؟ يبقى المرشحون الحاليون.',
    jobsCloseConfirmBody: 'الإغلاق يوقف الاستقبال لهذه الوظيفة. يمكن إعادة فتحها لاحقًا.',
    jobsCloseConfirmActive: 'يبقى {count} مرشحًا نشطًا في المسار.',
    jobsReopenConfirm: 'إعادة فتح هذه الوظيفة لقبول الطلبات؟',
    jobsReopenConfirmBody: 'سيُستأنف استقبال طلبات APPLY لهذه الوظيفة.',
    jobsResumeConfirm: 'استئناف هذه الوظيفة الموقوفة؟',
    jobsResumeConfirmBody: 'سيُستأنف استقبال APPLY حتى الإيقاف أو الإغلاق.',
    jobsRemaining: '{remaining} متبقي من {total}',
    jobsAgeDays: '{days} يومًا',
    jobsIntakeOpen: 'يقبل الطلبات',
    jobsIntakeClosed: 'لا يقبل الطلبات',
    jobsShareUnavailable: 'المشاركة الخارجية غير متاحة لهذه الوظيفة.',
    jobsShareReady: 'جاهزة للمشاركة مع المرشحين',
    jobsEligibilityReason: 'حالة قبول الطلبات',
    jobsEligibility_job_not_accepting: 'لا يقبل الطلبات',
    jobsEligibility_job_paused: 'متوقفة مؤقتاً — لا تقبل الطلبات',
    jobsEligibility_job_closed: 'مغلقة — لا تقبل الطلبات',
    jobsEligibility_job_deadline_passed: 'انتهى موعد التقديم',
    jobsEligibility_job_vacancies_exhausted: 'لا توجد شواغر متبقية',
    jobsEligibility_job_visibility_denied: 'داخلية فقط — غير متاحة في واتساب المرشحين',
    jobsEligibility_job_content_incomplete: 'محتوى المرشح غير مكتمل أو غير معتمد',
    jobsEligibility_unknown: 'غير متاحة لمشاركة المرشحين',
    jobsApplicationLinkUnavailable: 'غير متاحة للمشاركة',
    jobsApplyCodeInternal: 'معرّف داخلي (ليس للمشاركة مع المرشحين)',
    jobsWsTabs: 'مساحة عمل الوظيفة',
    jobsWsTabOverview: 'نظرة عامة',
    jobsWsTabSharing: 'المشاركة',
    jobsWsTabApplicants: 'المتقدمون',
    jobsWsTabActivity: 'النشاط',
    jobsWsKeyFacts: 'أهم بيانات الوظيفة',
    jobsWsOverviewFactsHint: 'تظهر فقط تفاصيل الوظيفة المفيدة الحالية افتراضيًا.',
    jobsWsCandidateFacing: 'محتوى الظاهر للمرشح',
    jobsWsOverviewDescHint: 'ما يراه المرشحون لهذه الوظيفة.',
    jobsWsRequirements: 'المتطلبات',
    jobsWsNoRequirements: 'لا توجد متطلبات مهيكلة محفوظة لهذه الوظيفة بعد.',
    jobsWsSharingHint: 'كل ما تحتاجه لمشاركة هذه الوظيفة مع المرشحين.',
    jobsWsShareCard: 'مشاركة مع المرشحين',
    jobsWsApplyLink: 'رابط التقديم',
    jobsWsCopyCode: 'نسخ الرمز',
    jobsWsCopyLink: 'نسخ الرابط',
    jobsWsOpenLink: 'نسخ الرابط مرة أخرى',
    jobsWsQr: 'رمز QR',
    jobsWsQrHint: 'استخدمه على المطبوعات أو عند الاستقبال الشخصي.',
    jobsWsQrNotReady: 'رابط QR غير متاح لهذه الوظيفة بعد.',
    jobsWsDownloadQr: 'تنزيل QR',
    jobsWsFunnel: 'قمع المرشحين حسب المرحلة',
    jobsWsFunnelHint: 'كيف يتحرك المتقدمون لهذه الوظيفة بين المراحل.',
    jobsWsNoStageActivity: 'لم يدخل أي متقدم هذا المسار بعد.',
    jobsWsViewCandidates: 'عرض المرشحين',
    jobsWsRecentApplicants: 'أحدث المتقدمين',
    jobsWsRecentHint: 'آخر الأشخاص الذين تقدموا لهذه الوظيفة.',
    jobsWsNoApplicants: 'لم يستخدم أي متقدم رابط هذه الوظيفة بعد.',
    jobsWsCandidateActivity: 'نشاط التواصل مع المرشح',
    jobsWsActivityHint: 'أحدث محاولات التواصل مع المرشح المرتبطة بهذه الوظيفة.',
    jobsWsNoActivity: 'لا يوجد نشاط تواصل حديث لهذه الوظيفة.',
    jobsWsCandidateContact: 'تواصل مع المرشح',
    jobsFormDirty: 'تغييرات غير محفوظة',
    jobsFormClean: 'تم حفظ كل التغييرات',
    jobsFormSectionBasics: 'الأساسيات',
    jobsFormSectionBasicsHint: 'الاسم والرمز والظهور.',
    jobsFormSectionHiring: 'إعداد التوظيف',
    jobsFormSectionHiringHint: 'القسم والموقع ونظام العمل والشواغر.',
    jobsFormSectionContent: 'محتوى الظاهر للمرشح',
    jobsFormSectionContentHint: 'ما يراه المرشح بالإنجليزية والعربية.',
    jobsFormSectionAdvanced: 'متقدم / اختياري',
    jobsFormSectionAdvancedHint: 'العقد والراتب والملكية الداخلية.',
    jobsCloseWorkspace: 'إغلاق',
  },
} as const

export type RecruitingCopyKey = keyof (typeof COPY)['en']

export function recruitingCopy(locale: RecruitingLocale, key: RecruitingCopyKey, vars?: Record<string, string | number>): string {
  let text: string = COPY[locale][key]
  if (vars) {
    for (const [name, value] of Object.entries(vars)) {
      text = text.replace(`{${name}}`, String(value))
    }
  }
  return text
}

/** Backend-authoritative external share gate for Jobs share/QR controls. */
export function jobIsExternallyShareable(job: {
  shareable?: boolean | null
  application_link?: string | null
  qr_value?: string | null
  accepts_applications?: boolean | null
}): boolean {
  if (typeof job.shareable === 'boolean') return job.shareable
  return Boolean(job.application_link || job.qr_value) && job.accepts_applications !== false
}

const ELIGIBILITY_COPY_KEYS = {
  job_not_accepting: 'jobsEligibility_job_not_accepting',
  job_paused: 'jobsEligibility_job_paused',
  job_closed: 'jobsEligibility_job_closed',
  job_deadline_passed: 'jobsEligibility_job_deadline_passed',
  job_vacancies_exhausted: 'jobsEligibility_job_vacancies_exhausted',
  job_visibility_denied: 'jobsEligibility_job_visibility_denied',
  job_content_incomplete: 'jobsEligibility_job_content_incomplete',
} as const satisfies Record<string, RecruitingCopyKey>

export function jobEligibilityReasonLabel(locale: RecruitingLocale, reason: string | null | undefined): string {
  const key = reason ? ELIGIBILITY_COPY_KEYS[reason as keyof typeof ELIGIBILITY_COPY_KEYS] : undefined
  return recruitingCopy(locale, key || 'jobsEligibility_unknown')
}

export function canonicalStage(value: string | null | undefined): CanonicalApplicationStage | null {
  const normalized = String(value || '').trim().toLowerCase()
  if ((CANONICAL_APPLICATION_STAGES as readonly string[]).includes(normalized)) {
    return normalized as CanonicalApplicationStage
  }
  return LEGACY_STAGE_MAP[normalized] || null
}

export function canonicalStageLabel(value: string | null | undefined, locale: RecruitingLocale = 'en'): string {
  const stage = canonicalStage(value)
  return stage ? STAGE_LABELS[locale][stage] : locale === 'ar' ? 'مرحلة غير معروفة' : 'Unknown stage'
}

export function communicationState(value: string | null | undefined): CommunicationState {
  const normalized = String(value || '').trim().toLowerCase()
  if ((COMMUNICATION_STATES as readonly string[]).includes(normalized)) return normalized as CommunicationState
  if (['queued', 'retrying', 'throttled'].includes(normalized)) return 'pending'
  if (['delivered', 'completed', 'recovered'].includes(normalized)) return 'sent'
  if (['suppressed', 'dashboard_only', 'skipped'].includes(normalized)) return 'intentionally_skipped'
  if (normalized) return normalized.includes('fail') ? 'failed' : 'pending'
  return 'intentionally_skipped'
}

export function communicationLabel(value: string | null | undefined, locale: RecruitingLocale = 'en'): string {
  return COMMUNICATION_LABELS[locale][communicationState(value)]
}

export function facetStatusLabel(value: string | null | undefined, locale: RecruitingLocale = 'en'): string {
  const normalized = String(value || '').trim().toLowerCase()
  const labels: Record<string, [string, string]> = {
    received: ['Received', 'تم الاستلام'],
    not_received: ['Not received', 'لم يتم الاستلام'],
    completed: ['Completed', 'مكتملة'],
    complete: ['Complete', 'مكتملة'],
    in_progress: ['In progress', 'قيد التنفيذ'],
    not_started: ['Not started', 'لم تبدأ'],
    scheduled: ['Scheduled', 'مجدولة'],
    rescheduled: ['Rescheduled', 'أعيدت جدولتها'],
    no_show: ['No-show', 'لم يحضر'],
    cancelled: ['Cancelled', 'ملغاة'],
    confirmed: ['Confirmed', 'تم التأكيد'],
    not_confirmed: ['Not confirmed', 'لم يتم التأكيد'],
    not_requested: ['Not requested', 'لم يُطلب'],
    pending: ['Pending', 'قيد الانتظار'],
    notes_pending: ['Notes pending', 'الملاحظات معلّقة'],
    feedback_complete: ['Feedback complete', 'اكتملت الملاحظات'],
  }
  const label = labels[normalized]
  if (label) return label[locale === 'ar' ? 1 : 0]
  if (!normalized) return locale === 'ar' ? 'غير مسجّل' : 'Not recorded'
  return normalized.replaceAll('_', ' ')
}

export function actionLabel(value: string, locale: RecruitingLocale = 'en'): string {
  return ACTION_LABELS[locale][value] || value.replaceAll('_', ' ')
}

export function intakeSourceLabel(value: string | null | undefined, locale: RecruitingLocale = 'en'): string {
  const normalized = String(value || 'unknown').toLowerCase()
  const labels: Record<string, [string, string]> = {
    whatsapp: ['WhatsApp application', 'طلب عبر واتساب'],
    bulk_import: ['Bulk CV import', 'استيراد جماعي للسير الذاتية'],
    email: ['Recruiting email', 'البريد الإلكتروني للتوظيف'],
    manual: ['Manual entry', 'إدخال يدوي'],
    unknown: ['Source not recorded', 'المصدر غير مسجّل'],
  }
  const label = labels[normalized] || [normalized.replaceAll('_', ' '), normalized.replaceAll('_', ' ')]
  return label[locale === 'ar' ? 1 : 0]
}

export function workflowItemLabel(value: string, locale: RecruitingLocale = 'en'): string {
  const labels: Record<string, [string, string]> = {
    cv_received: ['CV received and stored', 'تم استلام السيرة الذاتية وحفظها'],
    cv_processed: ['CV processed', 'تمت معالجة السيرة الذاتية'],
    screening_updated: ['Screening facet updated', 'تم تحديث بيانات الفرز'],
    review_task_created: ['Ready-for-review task created', 'تم إنشاء مهمة جاهزة للمراجعة'],
    review_candidate: ['Review evidence and choose the next step', 'مراجعة الأدلة واختيار الخطوة التالية'],
    schedule_interview: ['Schedule the interview', 'جدولة المقابلة'],
    record_interview_notes: ['Record interview notes', 'تسجيل ملاحظات المقابلة'],
    decide_after_interview: ['Make the post-interview human decision', 'اتخاذ القرار البشري بعد المقابلة'],
    resolve_communication: ['Resolve the communication failure', 'معالجة فشل التواصل'],
    inform_candidate: ['Inform the candidate of the stage change', 'إبلاغ المرشح بتغيير المرحلة'],
    resolve_invitation: ['Resolve the invitation failure', 'معالجة فشل الدعوة'],
    send_invitation: ['Send the interview invitation', 'إرسال دعوة المقابلة'],
    record_notes: ['Record interview notes', 'تسجيل ملاحظات المقابلة'],
    decide_application: ['Choose the next application step', 'اختيار الخطوة التالية للطلب'],
    review_next_step: ['Review and choose the next step', 'المراجعة واختيار الخطوة التالية'],
    conduct_interview: ['Conduct the interview', 'إجراء المقابلة'],
  }
  const label = labels[value] || [value.replaceAll('_', ' '), value.replaceAll('_', ' ')]
  return label[locale === 'ar' ? 1 : 0]
}
